### PR TITLE
Update Tellor Implementation

### PR DESCRIPTION
**Pull request by piesrtasty**
## Update Tellor Implementation

- [x] Add new Tellor helper contracts (https://github.com/tellor-io/usingtellor/tree/master/contracts)
- [x]  Port new Tellor helper contracts to 0.6.7
- [x] Change our implementation to fetch prices 15 minutes in the past (https://www.liquity.org/blog/tellor-issue-and-fix)
- [x] Update test suite to account for changes

Outstanding Tasks (5 tests are not passing) - These are commented out with a `TODO` block above them

- [x] 1 in `TellorPriceFeedMedianizer.t.sol`
- [x] 4 in `TellorTWAP.t.sol`

Notes:

- Changed `getCurrentValue` calls to use `getDataBefore`. However the API has changed for `getDataBefore` and it no longer returns a `bool` indicating if it was successful. To account for this I wrapped the calls in `try / catch` blocks in order to trigger the same error we were before when not successful.

### CODE REVIEW

**Comment by tkernell** [comment]
Some of the Relayer tests seem to need some updates:
- `testFail_read_null_price` - need to warp time past timeDelay in order to read submitted null price. Also, should check for expected revert
- `testFail_read_stale_price` - should check for expected revert
- `test_read` - should check that expected value is returned from `read`

**Comment by lukehamilton** [comment]
@tkernell Thanks for the review. So I just added an explicit assertion for the value in `test_read` and am now warping the time in `testFail_read_null_price`. Regarding checking for reversions, that is inherently done by the test name being preceded by `testFail`, or are you referring to something else?

**Review by tkernell — APPROVED** [review]

**Comment by tkernell** [comment]
This PR is looking good. I wasn't familiar with that `testFail` wording, so that part can be ignored.

**Review by fabiohild — CHANGES_REQUESTED** [review]
PR is looking good! A couple of minor adjustments:
- Make sure to use safemath for all arithmetic operations (a couple of subtractions are missing, they are unlikely to overflow but we always err to the side of caution).
- Please make the vars that are set only on the constructor (and not through `modifyParameters`) immutable, vars declared as literals such as multiplier can be declared as constants for similar gas savings.

**Review by fabiohild — APPROVED** [review]

**Pull request merged**
